### ISSUE TITLE
Setting options through web interface

### ISSUE THREAD

**Issue by Neil-McK** [DCC-EX/DCCInspector-EX#3]
Currently, the options (NMRA validation particularly) can only be set through the serial interface.  It would be useful to be able to set this through a control on the web page.

**Comment by FrightRisk** [comment]
Looks like you can check this one off ;)

**Comment by Neil-McK** [comment]
I've spotted that the handling of long binary states is wrong, need to fix
that.  Away on holiday till Friday.

**Comment by Neil-McK** [comment]
Options for NMRA level, sample period, and filter on/off added in pull request #4.
