### ISSUE TITLE
Consistency with throttle commands in 28 and 128 speed step mode

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/DCCInspector-EX#7]
In 128 speed step mode we list the command as "Fwd128", but in 28 speed step mode we call is "Forw". Should it be consistent? Either just "Fwd" or perhaps better as "Fwd28". What do you think?

### Short Address 128 Speed Steps

```
Loc 3 Fwd128 40         00000011 00111111 10101001
Loc 3 Fwd128 Stop       00000011 00111111 10000000
```

### Short Address 28 Speed Steps <D SPEED28>

```
Loc 3 Forw 12           00000011 01110111 
Loc 3 Stop              00000011 01100000
```

**Comment by Neil-McK** [comment]
Modified in Pull Request #8.

**Comment by Neil-McK** [comment]
Fix was added to main branch in 2021 so issue closed.
